var fylkeList = [
  { nummer: "03", navn: "Oslo" },
  { nummer: "11", navn: "Rogaland" },
  { nummer: "15", navn: "Møre og Romsdal" },
  { nummer: "18", navn: "Nordland - Nordlánnda" },
  { nummer: "31", navn: "Østfold" },
  { nummer: "32", navn: "Akershus" },
  { nummer: "33", navn: "Buskerud" },
  { nummer: "34", navn: "Innlandet" },
  { nummer: "39", navn: "Vestfold" },
  { nummer: "40", navn: "Telemark" },
  { nummer: "42", navn: "Agder" },
  { nummer: "46", navn: "Vestland" },
  { nummer: "50", navn: "Trøndelag - Trööndelage" },
  { nummer: "55", navn: "Troms – Romsa – Tromssa" },
  { nummer: "56", navn: "Finnmark – Finnmárku – Finmarkku" },
];
